# Generated by Django 4.2.30 on 2026-06-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
