# Generated by Django 4.2.30 on 2026-06-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0002_alter_employe_matricule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeconge',
            options={'ordering': ['categorie', 'libelle'], 'verbose_name': 'Type de congé', 'verbose_name_plural': 'Types de congé'},
        ),
        migrations.AddField(
            model_name='typeconge',
            name='categorie',
            field=models.CharField(choices=[('conge', 'Congé'), ('absence', 'Absence')], default='conge', max_length=10),
        ),
    ]
