# Generated by Django 4.2.30 on 2026-06-12 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0003_alter_typeconge_options_typeconge_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='interimaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacements', to=settings.AUTH_USER_MODEL),
        ),
    ]
