# Generated by Django 4.2.30 on 2026-06-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0004_demandeconge_interimaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeconge',
            name='motif',
            field=models.TextField(blank=True),
        ),
    ]
