# Generated by Django 4.2.17 on 2026-07-28 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0005_alter_demandeconge_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='commentaire_validation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='valide_par',
            field=models.ForeignKey(blank=True, help_text='Manager/RH ayant effectué la première validation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandeconge',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée - en attente du DG'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='demandeconge',
            name='traite_par',
            field=models.ForeignKey(blank=True, help_text='DG ayant approuvé/rejeté définitivement la demande, ou auteur du rejet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employe',
            name='role',
            field=models.CharField(choices=[('employe', 'Employé'), ('manager', 'Manager'), ('rh', 'Responsable RH'), ('dg', 'Directeur Général'), ('admin', 'Administrateur')], default='employe', max_length=20),
        ),
    ]
