# Generated by Django 6.0.6 on 2026-07-30 10:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0006_demandeconge_commentaire_validation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_depart', models.CharField(choices=[('demission', 'Démission'), ('licenciement', 'Licenciement'), ('fin_contrat', 'Fin de contrat'), ('retraite', 'Retraite'), ('rupture_conventionnelle', 'Rupture conventionnelle'), ('deces', 'Décès'), ('autre', 'Autre')], default='demission', max_length=30)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('finalise', 'Finalisé')], default='planifie', max_length=20)),
                ('date_annonce', models.DateField(default=datetime.date.today)),
                ('date_depart', models.DateField(help_text='Dernier jour de travail effectif')),
                ('preavis_jours', models.PositiveIntegerField(blank=True, null=True)),
                ('motif', models.TextField(blank=True)),
                ('entretien_sortie_effectue', models.BooleanField(default=False)),
                ('solde_tout_compte_effectue', models.BooleanField(default=False)),
                ('materiel_restitue', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departs', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departs_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Départ',
                'verbose_name_plural': 'Départs',
                'ordering': ['-date_depart'],
            },
        ),
        migrations.CreateModel(
            name='Recrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('consultant', 'Consultant')], default='cdi', max_length=20)),
                ('source', models.CharField(blank=True, choices=[('candidature_spontanee', 'Candidature spontanée'), ('cooptation', 'Cooptation'), ('cabinet_recrutement', 'Cabinet de recrutement'), ('site_emploi', "Site d'emploi"), ('reseau_social', 'Réseau social'), ('autre', 'Autre')], max_length=30)),
                ('statut', models.CharField(choices=[('essai', "Période d'essai"), ('confirme', 'Confirmé'), ('rompu', "Rompu pendant la période d'essai")], default='essai', max_length=20)),
                ('date_embauche', models.DateField(default=datetime.date.today)),
                ('periode_essai_fin', models.DateField(blank=True, null=True)),
                ('contrat_signe', models.BooleanField(default=False)),
                ('visite_medicale_effectuee', models.BooleanField(default=False)),
                ('dossier_complet', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recrutements', to=settings.AUTH_USER_MODEL)),
                ('responsable_rh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recrutements_geres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recrutement',
                'verbose_name_plural': 'Recrutements',
                'ordering': ['-date_embauche'],
            },
        ),
    ]
