# Generated by Django 6.0.6 on 2026-07-30 10:56

import conges.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0007_depart_recrutement'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldeconge',
            name='jours_supplementaires',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='CongeSupplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(default=conges.models._annee_courante)),
                ('nombre_jours', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('accorde_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_supplementaires_accordes', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges_supplementaires', to=settings.AUTH_USER_MODEL)),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conges.typeconge')),
            ],
            options={
                'verbose_name': 'Congé supplémentaire',
                'verbose_name_plural': 'Congés supplémentaires',
                'ordering': ['-date_creation'],
            },
        ),
    ]
