# Generated by Django 4.2.17 on 2026-08-03 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0008_soldeconge_jours_supplementaires_congesupplementaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='commentaire_validation_rh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='date_validation_rh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='valide_par_rh',
            field=models.ForeignKey(blank=True, help_text='Responsable RH ayant validé la demande avant transmission au DG.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validees_rh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandeconge',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee_manager', 'Validée par le manager - en attente du RH'), ('validee', 'Validée par le RH - en attente du DG'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='demandeconge',
            name='valide_par',
            field=models.ForeignKey(blank=True, help_text='Manager ayant effectué la première validation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validees', to=settings.AUTH_USER_MODEL),
        ),
    ]
