# Generated by Django 4.2.17 on 2026-08-03 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0009_demandeconge_commentaire_validation_rh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('demande_modifiee', 'Modification de demande de congé'), ('conge_supplementaire', 'Congé supplémentaire accordé')], max_length=30)),
                ('description', models.TextField()),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_effectuees', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to='conges.demandeconge')),
                ('employe_concerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de modification',
                'verbose_name_plural': 'Historique des modifications',
                'ordering': ['-date_action'],
            },
        ),
    ]
