# Generated by Django 4.2.17 on 2026-08-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0010_historiquemodification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquemodification',
            name='type_action',
            field=models.CharField(choices=[('demande_modifiee', 'Modification de demande de congé'), ('conge_supplementaire', 'Congé supplémentaire accordé'), ('solde_modifie', 'Modification de solde')], max_length=30),
        ),
    ]
