# Generated by Django 5.2.14 on 2026-08-17 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0011_alter_historiquemodification_type_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeconge',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'pdf', 'png'])]),
        ),
        migrations.AlterField(
            model_name='employe',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'jpeg', 'jpg', 'png', 'webp'])]),
        ),
    ]
