# Generated by Django 5.2.14 on 2026-09-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0012_alter_demandeconge_justificatif_alter_employe_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquemodification',
            name='type_action',
            field=models.CharField(choices=[('demande_modifiee', 'Modification de demande de congé'), ('conge_supplementaire', 'Congé supplémentaire accordé'), ('solde_modifie', 'Modification de solde'), ('employe_modifie', 'Modification de fiche employé'), ('employe_desactive', 'Compte employé désactivé'), ('employe_reactive', 'Compte employé réactivé')], max_length=30),
        ),
    ]
