# Generated by Django 5.2.14 on 2026-09-02 11:36

from django.db import migrations, models


def basculer_role_manager_vers_employe(apps, schema_editor):
    """The 'manager' role is retired: approval authority at the first-line
    stage now comes purely from the `manager` FK (who reports to whom),
    not from a role value — see Employe.is_manager_or_above. Anyone who
    had role='manager' keeps every one of their subordonnes exactly as
    before (the FK relationships are untouched) and keeps whatever
    approval rights that relationship grants; only the now-meaningless
    role label changes."""
    Employe = apps.get_model('conges', 'Employe')
    Employe.objects.filter(role='manager').update(role='employe')


def revenir_en_arriere(apps, schema_editor):
    # Irreversible on purpose: we can't tell apart, after the fact, which
    # 'employe' rows used to be 'manager' — reversing this migration is a
    # no-op rather than a guess.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0013_alter_historiquemodification_type_action'),
    ]

    operations = [
        migrations.RunPython(basculer_role_manager_vers_employe, revenir_en_arriere),
        migrations.AlterField(
            model_name='demandeconge',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee_manager', 'Validée par le supérieur direct - en attente du RH'), ('validee', 'Validée par le RH - en attente du DG'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='employe',
            name='role',
            field=models.CharField(choices=[('employe', 'Employé'), ('rh', 'Responsable RH'), ('dg', 'Directeur Général'), ('admin', 'Administrateur')], default='employe', max_length=20),
        ),
    ]
